name: hesap
description: QR kod ile Ã¶deme

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  #get_it: ^7.2.0
  qr_code_scanner: ^1.0.0
  connectivity_plus: ^4.0.1
  flutter_credit_card: ^3.0.1
  like_button: ^2.0.4
  animated_icon_button: ^1.0.2
  animated_splash_screen: ^1.2.0
  random_avatar: ^0.0.7
  animated_button: ^0.2.0
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/restoranlar.json
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu_regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu_bold.ttf
          weight: 700